# Copyright (c) 2026 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

from __future__ import annotations

from typing import Dict, List

from nuplan.common.maps.maps_datatypes import SemanticMapLayer, StopLineType


HD_MAP_GEOMETRY_TYPE_TO_ID = {
    "POLYLINE": 0,
    "POLYGON": 1,
}

HD_MAP_ELEMENT_TYPE_TO_ID = {
    "LANE_BASELINE": 0,
    "LANE_LEFT_BOUNDARY": 1,
    "LANE_RIGHT_BOUNDARY": 2,
    "LANE_CONNECTOR_BASELINE": 3,
    "LANE_CONNECTOR_LEFT_BOUNDARY": 4,
    "LANE_CONNECTOR_RIGHT_BOUNDARY": 5,
    "STOP_LINE": 6,
    "CROSSWALK": 7,
    "INTERSECTION": 8,
    "ROADBLOCK": 9,
    "ROADBLOCK_CONNECTOR": 10,
    "WALKWAYS": 11,
    "CARPARK_AREA": 12,
}

HD_MAP_POLYGON_LAYER_TO_ELEMENT_TYPE: Dict[SemanticMapLayer, int] = {
    SemanticMapLayer.STOP_LINE: HD_MAP_ELEMENT_TYPE_TO_ID["STOP_LINE"],
    SemanticMapLayer.CROSSWALK: HD_MAP_ELEMENT_TYPE_TO_ID["CROSSWALK"],
    SemanticMapLayer.INTERSECTION: HD_MAP_ELEMENT_TYPE_TO_ID["INTERSECTION"],
    SemanticMapLayer.ROADBLOCK: HD_MAP_ELEMENT_TYPE_TO_ID["ROADBLOCK"],
    SemanticMapLayer.ROADBLOCK_CONNECTOR: HD_MAP_ELEMENT_TYPE_TO_ID["ROADBLOCK_CONNECTOR"],
    SemanticMapLayer.WALKWAYS: HD_MAP_ELEMENT_TYPE_TO_ID["WALKWAYS"],
    SemanticMapLayer.CARPARK_AREA: HD_MAP_ELEMENT_TYPE_TO_ID["CARPARK_AREA"],
}

HD_MAP_DEFAULT_POLYGON_LAYER_NAMES: List[str] = [
    "STOP_LINE",
    "CROSSWALK",
    "INTERSECTION",
    "ROADBLOCK",
    "ROADBLOCK_CONNECTOR",
    "WALKWAYS",
    "CARPARK_AREA",
]

HD_MAP_SUPPORTED_POLYGON_LAYER_NAMES = sorted(layer.name for layer in HD_MAP_POLYGON_LAYER_TO_ELEMENT_TYPE)

HD_MAP_ON_ROUTE_UNKNOWN = 0
HD_MAP_ON_ROUTE_OFF = 1
HD_MAP_ON_ROUTE_ON = 2

HD_MAP_STOP_LINE_SUBTYPE_UNKNOWN = int(StopLineType.UNKNOWN)
